import Head from 'next/head'
import Link from 'next/link'
import { Provider } from 'react-redux'
import { store } from '../redux/store'


export default function Home() {
  return (
    <Provider store={store}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Link href='/dashboard/insight'>To Insight</Link>
    </Provider>
  )
}
